### ISSUE TITLE
Negative date containing an "X" will not validate

### ISSUE THREAD

**Issue by jenyoung** [unt-libraries/edtf-validate#15]
Trying to represent an uncertain date of `2nd century BC` with unspecified digits 

`-01XX` should validate but it does not.

**Comment by somexpert** [comment]
So there's actually two things that are going on here. First, you are absolutely right, we should be accepting negative values for dates that have the unspecified character. I'm gonna work on that. But another thing of note is that it looks like you might be referring to the [latest version](https://www.loc.gov/standards/datetime/edtf.html) of the spec, which is not what our current code is targeting. We actually built this to comply with the [draft specification](https://www.loc.gov/standards/datetime/pre-submission.html), which used 'u' instead of 'X' as the unspecified character. So, after I make a quick fix we should be able to validate `-01uu`, but we're not quite ready to support `-01XX` yet.

**Comment by somexpert** [comment]
This was partially addressed in #16. Since we aren't changing our target spec yet, I'm going to close this.
