### ISSUE TITLE
A string of "uuuu" currently validates as a valid EDTF

### ISSUE THREAD

**Issue by vphill** [unt-libraries/edtf-validate#2]
The string "uuuu" currently validates as a valid EDTF when in fact it is not.  Year only unspecified allows for the two right most character positions to be unspecified but no more than that. 

Also "1uuu" currently validates as well with EDTF.

http://www.loc.gov/standards/datetime/pre-submission.html#unspecified

Can be tested here (which uses ExtendedDateTimeFormat under the hood) - http://digital2.library.unt.edu/edtf/

**Comment by ldko** [comment]
This may be moot because EDTF may be changing (or we may just not want to allow this) anyway, but since I happened to be reading on this for another issue, I will note here that _technically_ (though maybe not sensibly) it looks like "uuuu" might be valid under [level 2](https://www.loc.gov/standards/datetime/pre-submission.html#partialunspecified)--later defined with:

```
level2Expression =   internalUncertainOrApproximate
                         | internalUnspecified 
                         | choiceList
                         |inclusiveList 
                         |maskedPrecision
                         | L2Interval 
                         |longYearScientific
                         |seasonQualified 

...

internalUnspecified = 
     yearWithU
   | yearMonthWithU
   | yearMonthDayWithU
 
      yearWithU = 
               "u" digitOrU digitOrU digitOrU 
             | digitOrU  "u" digitOrU digitOrU
             | digitOrU  digitOrU "u" digitOrU
             | digitOrU  digitOrU digitOrU "u"
...
```

**Comment by ldko** [comment]
According to the [specification ](https://www.loc.gov/standards/datetime/edtf.html)I believe 'XXXX' is a valid date in Level 2: "For level 2 the unspecified digit, 'X', may occur anywhere within a component," so I am closing this.

**Comment by mielvds** [comment]
@ldko I wonder why 'XXXX' would not be Level 1? "The character 'X' may be used in place of one or more rightmost digits to indicate that the value of that digit is unspecified", so why would an X as the first character not be allowed?

**Comment by ldko** [comment]
Hi @mielvds , thanks for commenting.

 I think the wording was more clear regarding this in the [2012 draft specification](https://web.archive.org/web/20190905015619/http://www.loc.gov:80/standards/datetime/pre-submission.html#unspecified) (when `u` was used instead of `X`) which is what this `edtf-validate` tool was originally based and also included the Backus–Naur Form mentioned in the comment above from 2016. Regarding what you quoted from the updated specification, it does make it sound like it would be Level 1, but with the rest of the wording  included: "The character 'X' may be used in place of one or more rightmost digits to indicate that the value of that digit is unspecified, **for the following cases: 1. A year with one or two (rightmost) unspecified digits in a year-only expression (year precision)** . Based on that and what's in the earlier draft, I interpret it to mean, it still must only be `X` in the one or two rightmost digits for Level 1, and if it is `X` in more than those 2 places, it validates under the Level 2 rule of "the unspecified digit, 'X', may occur anywhere within a component.". If you find something else that contradicts my interpretation, let us know, we can update the tool.
